### ISSUE TITLE
CreeperHeal Imcompatibility with other plugins

### ISSUE THREAD

**Issue by Arhke** [pmdevita/CreeperHeal2#24]
Spent a couple hours debugging a plugin fork and realized that some plugin set all of the blocks in the blocklist of EntityExplodeEvent to AIR. Using Plugman... found out that creeperheal was the culprit of this... Bug can be recreated with any EntityExplodeEvent with EventPriority.MONITOR

**Comment by pmdevita** [comment]
This is intended behavior, in order to avoid the explosion dropping items (particularly a problem with chests and containers), the explosion blocks are removed and replaced with air. What plugin are you working with or what are you trying to do?

**Comment by Arhke** [comment]
Was trying to make it work with a plugin called blowable obsidian... What it does (I modified it to do) is it takes the the Blocklist of blown up blocks and if it's not air, then it takes off health from the block (think obsidian destroyer from factions but for every block)...

Was able to get past this bug late last night by modifying the priority to monitor of creeperheal's block and entity explode event. 


I can't think of any problems with doing this (changing the priority) off of the top of my head, but maybe doing so will cause issues with some other plugin I can't really say for sure... ... ...

**Comment by pmdevita** [comment]
https://github.com/SpillereNO/BlowableObsidians/blob/04cfd9eafcefa89e20e97bd74eda30a6ee060f97/src/no/spillere/blowable/listeners/Listener.java#L30 The event listeners in the Blowable Obsidian plugin are all using MONITOR level priority, which is a bad practice since this priority should only be used for [monitoring (not editing) the outcome of an event](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/EventPriority.html). This prevents other plugins from being able to prioritize after it (such as CreeperHeal), causing compatibility problems. In general, it's a little strange to see all of the events being set to MONITOR along with `ignoreCancelled=true`, this is the kind of thing you do as a last ditch effort or under very specific, odd circumstances, which this plugin doesn't fall into.

You should adjust all of the events back to NORMAL to start with. Your onBlockBreak and onPlayerInteract events can definitely lose `ignoreCancelled` without any issues and I think it would be best if your explosion handling events did too.

Then from there, you can adjust the priority as you notice compatibility problems. My guess would be if you did have to adjust from NORMAL, it would be to LOW to make sure your plugin can remove blocks before other plugins touch them. But try NORMAL first.

I set CreeperHeal's priority to HIGH to make sure that all of the NORMAL and lower priorities could complete first since they would need to be able to read the original block list. But you do make a good point, that given how the plugin completely empties the block list and plugins running after it would have nothing to work with, it might be better to increase the priority to HIGHEST. I'll keep that in mind, although I'd like to see an example compatibility issue with another plugin first before I do so to make sure.
